In [2]:
import os
os.getcwd()

'/Users/brandonstoia/Desktop/MADS/Term 3/Session 1/SIADS 696 - Milestone II/walkanalysis/notebooks'

In [118]:
import pandas as pd

mod = pd.read_parquet("../artifacts/model/county_model_table.parquet")
mod

,STATEFP,COUNTYFP,walkability_min,walkability_max,walkability_mean,walkability_median,Ac_Total,Ac_Land,Ac_Unpr,Ac_Water,...,edu_total_pop_25plus,edu_high_school_grad,edu_bachelor_degree,edu_masters_degree,edu_professional_degree,edu_doctorate_degree,state,county,year,GEO_ID_y
0,01,001,1.333333,10.000000,5.234375,4.666667,3.867879e+05,3.804357e+05,373158.784172,6352.190063,...,39614.0,10458.0,6507.0,3649.0,524.0,464.0,01,001,2021,01001
1,01,003,1.000000,12.500000,6.450355,6.250000,1.297424e+06,1.017464e+06,932574.210538,279959.572480,...,161977.0,36186.0,33379.0,13884.0,3059.0,2240.0,01,003,2021,01003
2,01,005,2.000000,11.000000,5.188406,4.666667,5.788771e+05,5.663928e+05,534293.333471,12484.285931,...,17995.0,5204.0,1212.0,520.0,164.0,111.0,01,005,2021,01005
3,01,007,2.000000,9.500000,5.033333,4.833333,4.007393e+05,3.983666e+05,318129.780484,2372.676192,...,16057.0,5556.0,1276.0,476.0,93.0,68.0,01,007,2021,01007
4,01,009,1.833333,8.500000,4.666667,4.500000,4.163930e+05,4.126827e+05,412305.399557,3710.321896,...,40668.0,11019.0,3783.0,1812.0,286.0,180.0,01,009,2021,01009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3214,72,145,1.000000,7.333333,4.359649,4.166667,4.363111e+04,2.934191e+04,28560.726899,14289.197491,...,39632.0,11200.0,6627.0,1945.0,208.0,208.0,72,145,2021,72145
3215,72,147,1.000000,6.000000,3.190476,2.333333,1.689507e+05,3.250388e+04,14005.014806,136446.845550,...,5970.0,2635.0,424.0,209.0,0.0,212.0,72,147,2021,72147
3216,72,149,1.333333,7.000000,3.254902,3.000000,2.370213e+04,2.280698e+04,22806.976400,895.154097,...,15523.0,5072.0,2658.0,535.0,51.0,89.0,72,149,2021,72149
3217,72,151,1.000000,7.333333,3.402778,2.833333,5.327419e+04,3.533658e+04,35006.627088,17937.610704,...,22690.0,5639.0,3353.0,511.0,34.0,53.0,72,151,2021,72151
3218,72,153,2.333333,7.333333,4.559524,4.833333,4.373600e+04,4.333440e+04,41374.334153,401.601499,...,25661.0,8381.0,5090.0,1075.0,134.0,352.0,72,153,2021,72153

In [167]:
import numpy as np
import pandas as pd

file_path = "/Users/brandonstoia/Desktop/MADS/Term 3/Session 1/SIADS 696 - Milestone II/ICPSR_38795/DS0001/38795-0001-Data.tsv"

df = pd.read_csv(
    file_path,
    sep="\t",
    low_memory=False,
    usecols=range(77)
)

cols = df.columns[33:77]
jcols = df.columns[22:31]

df[cols] = (
    df[cols]
        .astype(str)
        .apply(lambda x: x.str.strip().str.replace(" ", "", regex=False))
        .replace({"": np.nan, "99999": np.nan, "99998": np.nan})
        .apply(pd.to_numeric, errors="coerce")
)

df["TOTAL"] = df[cols].sum(axis=1, skipna=True)
df['OFFENSE'] = df['OFFENSE'].astype(str).str.zfill(3).replace({"018": "18", "019": "19"})
df = df.drop(columns=list(jcols) + list(cols))

df = (
    df
        .groupby(["ORI", "OFFENSE"], as_index=False)["TOTAL"]
        .sum()
)

df

            ORI OFFENSE  TOTAL
0       AK00102     011    2.0
1       AK00102     020    1.0
2       AK00102     030   13.0
3       AK00102     040   59.0
4       AK00102     050   23.0
...         ...     ...    ...
199426  WYDI050     220    4.0
199427  WYDI050     240   98.0
199428  WYDI050     250    1.0
199429  WYDI050     260  264.0
199430  WYWHP00     998    0.0

[199431 rows x 3 columns]

In [168]:
crimemap = pd.DataFrame([
    {"value":"011","label":"Murder and Non-Negligent Manslaughter","crime_against":"Person"},
    {"value":"012","label":"Manslaughter by Negligence","crime_against":"Person"},
    {"value":"020","label":"Forcible Rape","crime_against":"Person"},
    {"value":"030","label":"Robbery","crime_against":"Person"},
    {"value":"040","label":"Aggravated Assault","crime_against":"Person"},
    {"value":"050","label":"Burglary - Breaking or Entering","crime_against":"Property"},
    {"value":"060","label":"Larceny - Theft (except motor vehicle)","crime_against":"Property"},
    {"value":"070","label":"Motor Vehicle Theft","crime_against":"Property"},
    {"value":"080","label":"Other Assaults","crime_against":"Person"},
    {"value":"090","label":"Arson","crime_against":"Property"},
    {"value":"100","label":"Forgery and Counterfeiting","crime_against":"Property"},
    {"value":"110","label":"Fraud","crime_against":"Property"},
    {"value":"120","label":"Embezzlement","crime_against":"Property"},
    {"value":"130","label":"Stolen property \"Buying, Receiving, Poss.\"","crime_against":"Property"},
    {"value":"140","label":"Vandalism","crime_against":"Property"},
    {"value":"150","label":"Weapons - Carrying, Possessing, etc.","crime_against":"Society"},
    {"value":"160","label":"Prostitution and Commercialized Vice Total","crime_against":"Society"},
    {"value":"161","label":"Prostitution and Commercialized Vice - Prostitution","crime_against":"Society"},
    {"value":"162","label":"Prostitution and Commercialized Vice - Assisting or Promoting Prostitution","crime_against":"Society"},
    {"value":"163","label":"Prostitution and Commercialized Vice - Purchasing Prostitution","crime_against":"Society"},
    {"value":"170","label":"Sex Offenses (except forcible rape and prostitution)","crime_against":"Person"},
    {"value":"18","label":"Drug Abuse Violations (Total)","crime_against":"Society"},
    {"value":"180","label":"Sale/Manufacturing (Subtotal)","crime_against":"Society"},
    {"value":"181","label":"Opium and Cocaine, and their derivatives (Morphine, Heroin)","crime_against":"Society"},
    {"value":"182","label":"Marijuana","crime_against":"Society"},
    {"value":"183","label":"Synthetic Narcotics - Manufactured Narcotics which can cause true drug addiction (Demerol, Methadones)","crime_against":"Society"},
    {"value":"184","label":"Other Dangerous Non-Narcotic Drugs (Barbiturates, Benzedrine)","crime_against":"Society"},
    {"value":"185","label":"Possession (Subtotal)","crime_against":"Society"},
    {"value":"186","label":"same as 181","crime_against":"Society"},
    {"value":"187","label":"same as 182","crime_against":"Society"},
    {"value":"188","label":"same as 183","crime_against":"Society"},
    {"value":"189","label":"same as 184","crime_against":"Society"},
    {"value":"19","label":"Gambling (Total)","crime_against":"Society"},
    {"value":"191","label":"Bookmaking (Horse and Sport Book)","crime_against":"Society"},
    {"value":"192","label":"Number and Lottery","crime_against":"Society"},
    {"value":"193","label":"All Other Gambling","crime_against":"Society"},
    {"value":"200","label":"Offenses Against Family and Children","crime_against":"Person"},
    {"value":"210","label":"Driving Under the Influence","crime_against":"Society"},
    {"value":"220","label":"Liquor Laws","crime_against":"Society"},
    {"value":"230","label":"Drunkenness","crime_against":"Society"},
    {"value":"240","label":"Disorderly Conduct","crime_against":"Society"},
    {"value":"250","label":"Vagrancy","crime_against":"Society"},
    {"value":"260","label":"All Other Offenses (except traffic)","crime_against":"Society"},
    {"value":"270","label":"Suspicion","crime_against":"Society"},
    {"value":"280","label":"Curfew and Loitering Law Violations","crime_against":"Society"},
    {"value":"290","label":"Runaways","crime_against":"Society"},
    {"value":"301","label":"Human Trafficking - Commercial Sex Acts (300)","crime_against":"Person"},
    {"value":"302","label":"Human Trafficking - Involuntary Servitude (310)","crime_against":"Person"},
    {"value":"990","label":"(99) is assigned to Juvenile Disposition data. If included should be zero.","crime_against":"Society"},
    {"value":"998","label":"Not applicable","crime_against":None},
    {"value":"Total","label":"Total","crime_against":None},
])

crimemap

    value                                              label crime_against
0     011              Murder and Non-Negligent Manslaughter        Person
1     012                         Manslaughter by Negligence        Person
2     020                                      Forcible Rape        Person
3     030                                            Robbery        Person
4     040                                 Aggravated Assault        Person
5     050                    Burglary - Breaking or Entering      Property
6     060             Larceny - Theft (except motor vehicle)      Property
7     070                                Motor Vehicle Theft      Property
8     080                                     Other Assaults        Person
9     090                                              Arson      Property
10    100                         Forgery and Counterfeiting      Property
11    110                                              Fraud      Property
12    120                                       Embezzlement      Property
13    130         Stolen property "Buying, Receiving, Poss."      Property
14    140                                          Vandalism      Property
15    150               Weapons - Carrying, Possessing, etc.       Society
16    160         Prostitution and Commercialized Vice Total       Society
17    161  Prostitution and Commercialized Vice - Prostit...       Society
18    162  Prostitution and Commercialized Vice - Assisti...       Society
19    163  Prostitution and Commercialized Vice - Purchas...       Society
20    170  Sex Offenses (except forcible rape and prostit...        Person
21     18                      Drug Abuse Violations (Total)       Society
22    180                      Sale/Manufacturing (Subtotal)       Society
23    181  Opium and Cocaine, and their derivatives (Morp...       Society
24    182                                          Marijuana       Society
25    183  Synthetic Narcotics - Manufactured Narcotics w...       Society
26    184  Other Dangerous Non-Narcotic Drugs (Barbiturat...       Society
27    185                              Possession (Subtotal)       Society
28    186                                        same as 181       Society
29    187                                        same as 182       Society
30    188                                        same as 183       Society
31    189                                        same as 184       Society
32     19                                   Gambling (Total)       Society
33    191                  Bookmaking (Horse and Sport Book)       Society
34    192                                 Number and Lottery       Society
35    193                                 All Other Gambling       Society
36    200               Offenses Against Family and Children        Person
37    210                        Driving Under the Influence       Society
38    220                                        Liquor Laws       Society
39    230                                        Drunkenness       Society
40    240                                 Disorderly Conduct       Society
41    250                                           Vagrancy       Society
42    260                All Other Offenses (except traffic)       Society
43    270                                          Suspicion       Society
44    280                Curfew and Loitering Law Violations       Society
45    290                                           Runaways       Society
46    301      Human Trafficking - Commercial Sex Acts (300)        Person
47    302    Human Trafficking - Involuntary Servitude (310)        Person
48    990  (99) is assigned to Juvenile Disposition data....       Society
49    998                                     Not applicable          None
50  Total                                              Total          None

In [169]:
df = df.reset_index(drop=True)
df

            ORI OFFENSE  TOTAL
0       AK00102     011    2.0
1       AK00102     020    1.0
2       AK00102     030   13.0
3       AK00102     040   59.0
4       AK00102     050   23.0
...         ...     ...    ...
199426  WYDI050     220    4.0
199427  WYDI050     240   98.0
199428  WYDI050     250    1.0
199429  WYDI050     260  264.0
199430  WYWHP00     998    0.0

[199431 rows x 3 columns]

In [170]:
#df = 
df2 = df.merge(crimemap, left_on="OFFENSE", right_on="value", how="left").pivot_table(
          index="ORI",
          columns="crime_against",
          values="TOTAL",
          aggfunc="sum",
          fill_value=0
      ).reset_index()
df2.columns.name = None

In [181]:
df2[df2['Society']==df2['Society'].max()]

          ORI   Person  Property    Society
7410  NV00201  18351.0    7550.0  7161887.0

In [182]:
x[x['ORI'] == "NV00201"]

label,ORI,Aggravated Assault,All Other Gambling,All Other Offenses (except traffic),Arson,Burglary - Breaking or Entering,Curfew and Loitering Law Violations,Disorderly Conduct,Driving Under the Influence,Drug Abuse Violations (Total),...,"Stolen property ""Buying, Receiving, Poss.""",Suspicion,"Synthetic Narcotics - Manufactured Narcotics which can cause true drug addiction (Demerol, Methadones)",Vagrancy,Vandalism,"Weapons - Carrying, Possessing, etc.",same as 181,same as 182,same as 183,same as 184
7990,NV00201,2955.0,0.0,15136.0,69.0,1181.0,69.0,1142.0,4964.0,2275870.0,...,1062.0,0.0,7.0,133.0,1209.0,2417.0,1050.0,521.0,74.0,3154.0

In [178]:
x = df.merge(crimemap, left_on="OFFENSE", right_on="value", how="left").pivot_table(
          index="ORI",
          columns="label",
          values="TOTAL",
          aggfunc="sum",
          fill_value=0
      ).reset_index()

x[x['ORI'] == "AL0430000"]

Empty DataFrame
Columns: [ORI, Aggravated Assault, All Other Gambling, All Other Offenses (except traffic), Arson, Burglary - Breaking or Entering, Curfew and Loitering Law Violations, Disorderly Conduct, Driving Under the Influence, Drug Abuse Violations (Total), Drunkenness, Embezzlement, Forcible Rape, Forgery and Counterfeiting, Fraud, Gambling (Total), Human Trafficking - Commercial Sex Acts (300), Human Trafficking - Involuntary Servitude (310), Larceny - Theft (except motor vehicle), Liquor Laws, Manslaughter by Negligence, Marijuana, Motor Vehicle Theft, Murder and Non-Negligent Manslaughter, Not applicable, Offenses Against Family and Children, Opium and Cocaine, and their derivatives (Morphine, Heroin), Other Assaults, Other Dangerous Non-Narcotic Drugs (Barbiturates, Benzedrine), Possession (Subtotal), Prostitution and Commercialized Vice - Assisting or Promoting Prostitution, Prostitution and Commercialized Vice - Prostitution, Prostitution and Commercialized Vice - Purchasing Prostitution, Prostitution and Commercialized Vice Total, Robbery, Runaways, Sale/Manufacturing (Subtotal), Sex Offenses (except forcible rape and prostitution), Stolen property "Buying, Receiving, Poss.", Suspicion, Synthetic Narcotics - Manufactured Narcotics which can cause true drug addiction (Demerol, Methadones), Vagrancy, Vandalism, Weapons - Carrying, Possessing, etc., same as 181, same as 182, same as 183, same as 184]
Index: []

[0 rows x 48 columns]

In [ ]:
df2 = (
    df.merge(crimemap[["value", "label"]], left_on="OFFENSE", right_on="value", how="left")
      .assign(OFFENSE_NAME=lambda d: d["label"].fillna(d["OFFENSE"].astype(str)))
      .pivot_table(
          index="ORI",
          columns="OFFENSE_NAME",
          values="TOTAL",
          aggfunc="sum",
          fill_value=0
      )
      .reset_index()
      .drop(columns=["value", "label"], errors="ignore")
      #.drop(columns=["value", "label"], errors="ignore")
)

df2.columns.name = None
df2

,ORI,100,11,110,12,120,130,140,150,160,...,30,301,302,40,50,60,70,80,90,998
0,AK00102,3.0,2.0,12.0,0.0,0.0,0.0,44.0,30.0,0.0,...,13.0,0.0,0.0,59.0,23.0,63.0,28.0,183.0,1.0,0.0
1,AK00104,0.0,0.0,1.0,0.0,0.0,0.0,8.0,3.0,0.0,...,0.0,0.0,0.0,10.0,1.0,12.0,0.0,38.0,0.0,0.0
2,AK00105,1.0,0.0,1.0,0.0,0.0,0.0,7.0,4.0,0.0,...,2.0,0.0,0.0,10.0,2.0,2.0,1.0,42.0,0.0,0.0
3,AK00106,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1.0,0.0,...,0.0,0.0,0.0,9.0,1.0,4.0,6.0,140.0,0.0,0.0
4,AK00107,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,3.0,0.0,14.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13352,WY02201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,27.0,1.0,14.0,1.0,0.0
13353,WY02300,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,2.0,2.0,3.0,1.0,4.0,0.0,0.0
13354,WY02301,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,1.0,4.0,0.0,0.0
13355,WYDI050,0.0,0.0,1.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,6.0,5.0,1.0,2.0,16.0,0.0,0.0
13356,WYWHP00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [81]:
df2[crimemap['value'].unique()]

KeyError: "['011', '012', '020', '030', '040', '050', '060', '070', '080', '090', '191', '192', '990', 'Total'] not in index"

---

In [ ]:
from pathlib import Path
import pandas as pd
import geopandas as gpd
import shapely
artifacts_dir = Path("../artifacts")

walk = pd.read_parquet(artifacts_dir / "epa_walkability_county.parquet")
acs = pd.read_parquet(artifacts_dir / "acs_county_2021.parquet")
shapes = pd.read_parquet(artifacts_dir / "us_counties_shapes.parquet")
shapes = gpd.GeoDataFrame(shapes, geometry=shapely.from_wkb(shapes["geometry"]), crs="EPSG:4326")
countyfips = pd.read_parquet(artifacts_dir / "fips_counties.parquet")
statefips = pd.read_parquet(artifacts_dir / "fips_states.parquet")
agencies = pd.read_parquet(artifacts_dir / "fbi_agencies.parquet")
crime = pd.read_parquet(artifacts_dir / "crime_by_ori.parquet")

In [139]:
walk

,STATEFP,COUNTYFP,walkability_min,walkability_max,walkability_mean,walkability_median,Ac_Total,Ac_Land,Ac_Unpr,Ac_Water,GEO_ID,walkability_range
0,01,001,1.333333,10.000000,5.234375,4.666667,3.867879e+05,3.804357e+05,373158.784172,6352.190063,01001,8.666667
1,01,003,1.000000,12.500000,6.450355,6.250000,1.297424e+06,1.017464e+06,932574.210538,279959.572480,01003,11.500000
2,01,005,2.000000,11.000000,5.188406,4.666667,5.788771e+05,5.663928e+05,534293.333471,12484.285931,01005,9.000000
3,01,007,2.000000,9.500000,5.033333,4.833333,4.007393e+05,3.983666e+05,318129.780484,2372.676192,01007,7.500000
4,01,009,1.833333,8.500000,4.666667,4.500000,4.163930e+05,4.126827e+05,412305.399557,3710.321896,01009,6.666667
...,...,...,...,...,...,...,...,...,...,...,...,...
3228,72,151,1.000000,7.333333,3.402778,2.833333,5.327419e+04,3.533658e+04,35006.627088,17937.610704,72151,6.333333
3229,72,153,2.333333,7.333333,4.559524,4.833333,4.373600e+04,4.333440e+04,41374.334153,401.601499,72153,5.000000
3230,78,010,1.000000,7.333333,4.201550,4.000000,2.128914e+05,5.335259e+04,51037.373077,159538.840469,78010,6.333333
3231,78,020,1.000000,6.666667,3.500000,3.166667,5.872788e+04,1.260172e+04,3506.500711,46126.152059,78020,5.666667
3232,78,030,1.000000,7.333333,4.631579,4.333333,1.974403e+05,2.004189e+04,19053.567043,177398.372235,78030,6.333333

In [140]:
acs

,total_pop,total_male_pop,total_female_pop,total_pop_under_18,median_age,vacant_houses,housing_units,median_income,median_rent,unemployed,...,edu_total_pop_25plus,edu_high_school_grad,edu_bachelor_degree,edu_masters_degree,edu_professional_degree,edu_doctorate_degree,state,county,year,GEO_ID
0,58239.0,28206.0,30033.0,13801.0,38.5,2314.0,24170.0,62660.0,870.0,752.0,...,39614.0,10458.0,6507.0,3649.0,524.0,464.0,01,001,2021,01001
1,227131.0,110781.0,116350.0,49026.0,43.4,34573.0,121763.0,64346.0,892.0,3994.0,...,161977.0,36186.0,33379.0,13884.0,3059.0,2240.0,01,003,2021,01003
2,25259.0,13361.0,11898.0,5264.0,40.2,2579.0,11667.0,36422.0,411.0,808.0,...,17995.0,5204.0,1212.0,520.0,164.0,111.0,01,005,2021,01005
3,22412.0,12300.0,10112.0,4612.0,39.7,1930.0,9013.0,54277.0,425.0,884.0,...,16057.0,5556.0,1276.0,476.0,93.0,68.0,01,007,2021,01007
4,58884.0,29530.0,29354.0,13683.0,41.1,3227.0,24527.0,52830.0,480.0,1554.0,...,40668.0,11019.0,3783.0,1812.0,286.0,180.0,01,009,2021,01009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,54544.0,26057.0,28487.0,9940.0,43.1,4896.0,24695.0,21507.0,407.0,3482.0,...,39632.0,11200.0,6627.0,1945.0,208.0,208.0,72,145,2021,72145
3217,8317.0,4239.0,4078.0,1557.0,43.6,2593.0,4967.0,14942.0,323.0,358.0,...,5970.0,2635.0,424.0,209.0,0.0,212.0,72,147,2021,72147
3218,22341.0,10796.0,11545.0,4530.0,42.0,1557.0,9380.0,20722.0,289.0,1464.0,...,15523.0,5072.0,2658.0,535.0,51.0,89.0,72,149,2021,72149
3219,31047.0,15000.0,16047.0,5514.0,44.9,2643.0,14548.0,17267.0,356.0,1506.0,...,22690.0,5639.0,3353.0,511.0,34.0,53.0,72,151,2021,72151
3220,34704.0,16548.0,18156.0,6149.0,45.5,5877.0,17713.0,16444.0,331.0,1992.0,...,25661.0,8381.0,5090.0,1075.0,134.0,352.0,72,153,2021,72153

In [141]:
shapes

,id,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,01001,01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.7179 32.4028..."
1,01009,01009,01,009,Blount,County,644.776,"POLYGON ((-86.5778 33.76532, -86.75914 33.8406..."
2,01017,01017,01,017,Chambers,County,596.531,"POLYGON ((-85.18413 32.87052, -85.12342 32.772..."
3,01021,01021,01,021,Chilton,County,692.854,"POLYGON ((-86.51734 33.02057, -86.51596 32.929..."
4,01033,01033,01,033,Colbert,County,592.619,"POLYGON ((-88.13999 34.5817, -88.13925 34.5878..."
...,...,...,...,...,...,...,...,...
3104,51001,51001,51,001,Accomack,County,449.496,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ..."
3105,51021,51021,51,021,Bland,County,357.725,"POLYGON ((-81.2251 37.23487, -81.20477 37.2430..."
3106,51027,51027,51,027,Buchanan,County,502.763,"POLYGON ((-81.9683 37.5378, -81.92787 37.51212..."
3107,51037,51037,51,037,Charlotte,County,475.271,"POLYGON ((-78.44332 37.0794, -78.49303 36.8912..."
3108,51041,51041,51,041,Chesterfield,County,423.297,"POLYGON ((-77.8518 37.35487, -77.85515 37.4183..."

In [132]:
countyfips

       FIPS        County Name
0     01000            Alabama
1     01001     Autauga County
2     01003     Baldwin County
3     01005     Barbour County
4     01007        Bibb County
...     ...                ...
3190  56037  Sweetwater County
3191  56039       Teton County
3192  56041       Uinta County
3193  56043    Washakie County
3194  56045      Weston County

[3195 rows x 2 columns]

In [133]:
statefips

   FIPS            State Name
0    01               ALABAMA
1    02                ALASKA
2    04               ARIZONA
3    05              ARKANSAS
4    06            CALIFORNIA
5    08              COLORADO
6    09           CONNECTICUT
7    10              DELAWARE
8    11  DISTRICT OF COLUMBIA
9    12               FLORIDA
10   13               GEORGIA
11   15                HAWAII
12   16                 IDAHO
13   17              ILLINOIS
14   18               INDIANA
15   19                  IOWA
16   20                KANSAS
17   21              KENTUCKY
18   22             LOUISIANA
19   23                 MAINE
20   24              MARYLAND
21   25         MASSACHUSETTS
22   26              MICHIGAN
23   27             MINNESOTA
24   28           MISSISSIPPI
25   29              MISSOURI
26   30               MONTANA
27   31              NEBRASKA
28   32                NEVADA
29   33         NEW HAMPSHIRE
30   34            NEW JERSEY
31   35            NEW MEXICO
32   36              NEW YORK
33   37        NORTH CAROLINA
34   38          NORTH DAKOTA
35   39                  OHIO
36   40              OKLAHOMA
37   41                OREGON
38   42          PENNSYLVANIA
39   44          RHODE ISLAND
40   45        SOUTH CAROLINA
41   46          SOUTH DAKOTA
42   47             TENNESSEE
43   48                 TEXAS
44   49                  UTAH
45   50               VERMONT
46   51              VIRGINIA
47   53            WASHINGTON
48   54         WEST VIRGINIA
49   55             WISCONSIN
50   56               WYOMING

In [146]:
agencies

,state,county,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date
0,AL,LEE,AL0430000,LEE,True,32.604064,-85.353048,AL,Alabama,Lee County Sheriff's Office,County,2012-04-01
1,AL,LEE,AL0430200,LEE,True,32.604064,-85.353048,AL,Alabama,Opelika Police Department,City,2021-01-01
2,AL,LEE,AL0430100,LEE,True,32.608086,-85.475136,AL,Alabama,Auburn Police Department,City,2020-12-01
3,AL,BIBB,AL0070300,BIBB,True,33.015893,-87.127148,AL,Alabama,West Blocton Police Department,City,2020-01-01
4,AL,BIBB,AL0070200,BIBB,True,33.015893,-87.127148,AL,Alabama,Brent Police Department,City,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...
16106,WY,NOT SPECIFIED,WY0130800,NOT SPECIFIED,True,NaN,NaN,WY,Wyoming,Wyoming Gaming Commission,Other State Agency,2024-01-01
16107,WY,NOT SPECIFIED,WYDI05000,NOT SPECIFIED,True,43.055303,-108.605531,WY,Wyoming,Wind River Agency,Tribal,2021-01-01
16108,GU,NOT SPECIFIED,GM0010000,NOT SPECIFIED,True,NaN,NaN,GU,Guam,Guam Police Department,Other,2021-01-01
16109,DC,NOT SPECIFIED,DCMPD0000,NOT SPECIFIED,True,38.894764,-77.015205,DC,District of Columbia,Washington Police Department,City,2021-08-01
16110,DC,NOT SPECIFIED,DCMTP0000,NOT SPECIFIED,True,38.897390,-77.018940,DC,District of Columbia,Metro Transit Police,Other,2000-01-01

In [135]:
crime

           ORI  Person  Property  Society
0      AK00102   261.0     174.0    617.0
1      AK00104    51.0      22.0    123.0
2      AK00105    56.0      14.0     95.0
3      AK00106   154.0      18.0    324.0
4      AK00107    15.0       9.0     55.0
...        ...     ...       ...      ...
12392  WY02200    16.0       7.0     70.0
12393  WY02201    17.0      29.0    101.0
12394  WY02300     9.0       7.0     11.0
12395  WY02301     6.0       7.0     58.0
12396  WYDI050    34.0      14.0    498.0

[12397 rows x 4 columns]

In [143]:
shapes

,id,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,01001,01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.7179 32.4028..."
1,01009,01009,01,009,Blount,County,644.776,"POLYGON ((-86.5778 33.76532, -86.75914 33.8406..."
2,01017,01017,01,017,Chambers,County,596.531,"POLYGON ((-85.18413 32.87052, -85.12342 32.772..."
3,01021,01021,01,021,Chilton,County,692.854,"POLYGON ((-86.51734 33.02057, -86.51596 32.929..."
4,01033,01033,01,033,Colbert,County,592.619,"POLYGON ((-88.13999 34.5817, -88.13925 34.5878..."
...,...,...,...,...,...,...,...,...
3104,51001,51001,51,001,Accomack,County,449.496,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ..."
3105,51021,51021,51,021,Bland,County,357.725,"POLYGON ((-81.2251 37.23487, -81.20477 37.2430..."
3106,51027,51027,51,027,Buchanan,County,502.763,"POLYGON ((-81.9683 37.5378, -81.92787 37.51212..."
3107,51037,51037,51,037,Charlotte,County,475.271,"POLYGON ((-78.44332 37.0794, -78.49303 36.8912..."
3108,51041,51041,51,041,Chesterfield,County,423.297,"POLYGON ((-77.8518 37.35487, -77.85515 37.4183..."

In [156]:
ag = agencies.dropna(subset=["latitude","longitude"])
ag = gpd.GeoDataFrame(ag, geometry=gpd.points_from_xy(ag["longitude"], ag["latitude"]), crs="EPSG:4326")
agc = gpd.sjoin(ag, shapes, how="left", predicate="within", lsuffix="agency", rsuffix="county").drop(columns=['GEO_ID'], axis=1)
agc
#agc.head()

,state,county,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date,geometry,index_county,id,STATE,COUNTY,NAME,LSAD,CENSUSAREA
0,AL,LEE,AL0430000,LEE,True,32.604064,-85.353048,AL,Alabama,Lee County Sheriff's Office,County,2012-04-01,POINT (-85.35305 32.60406),659.0,01081,01,081,Lee,County,607.536
1,AL,LEE,AL0430200,LEE,True,32.604064,-85.353048,AL,Alabama,Opelika Police Department,City,2021-01-01,POINT (-85.35305 32.60406),659.0,01081,01,081,Lee,County,607.536
2,AL,LEE,AL0430100,LEE,True,32.608086,-85.475136,AL,Alabama,Auburn Police Department,City,2020-12-01,POINT (-85.47514 32.60809),659.0,01081,01,081,Lee,County,607.536
3,AL,BIBB,AL0070300,BIBB,True,33.015893,-87.127148,AL,Alabama,West Blocton Police Department,City,2020-01-01,POINT (-87.12715 33.01589),675.0,01007,01,007,Bibb,County,622.582
4,AL,BIBB,AL0070200,BIBB,True,33.015893,-87.127148,AL,Alabama,Brent Police Department,City,2020-01-01,POINT (-87.12715 33.01589),675.0,01007,01,007,Bibb,County,622.582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16104,WY,HOT SPRINGS,WY0090100,HOT SPRINGS,True,43.720871,-108.435652,WY,Wyoming,Thermopolis Police Department,City,2019-12-01,POINT (-108.43565 43.72087),1720.0,56017,56,017,Hot Springs,County,2004.092
16105,WY,NOT SPECIFIED,WYWHP0000,NOT SPECIFIED,True,41.167576,-104.841750,WY,Wyoming,Wyoming Highway Patrol,State Police,2023-01-01,POINT (-104.84175 41.16758),3099.0,56021,56,021,Laramie,County,2685.912
16107,WY,NOT SPECIFIED,WYDI05000,NOT SPECIFIED,True,43.055303,-108.605531,WY,Wyoming,Wind River Agency,Tribal,2021-01-01,POINT (-108.60553 43.0553),3098.0,56013,56,013,Fremont,County,9183.814
16109,DC,NOT SPECIFIED,DCMPD0000,NOT SPECIFIED,True,38.894764,-77.015205,DC,District of Columbia,Washington Police Department,City,2021-08-01,POINT (-77.0152 38.89476),756.0,11001,11,001,District of Columbia,,61.048
16110,DC,NOT SPECIFIED,DCMTP0000,NOT SPECIFIED,True,38.897390,-77.018940,DC,District of Columbia,Metro Transit Police,Other,2000-01-01,POINT (-77.01894 38.89739),756.0,11001,11,001,District of Columbia,,61.048

In [157]:
agc['ori']

0        AL0430000
1        AL0430200
2        AL0430100
3        AL0070300
4        AL0070200
           ...
16104    WY0090100
16105    WYWHP0000
16107    WYDI05000
16109    DCMPD0000
16110    DCMTP0000
Name: ori, Length: 14232, dtype: object

In [155]:
crime['ORI']

0        AK00102
1        AK00104
2        AK00105
3        AK00106
4        AK00107
          ...
12392    WY02200
12393    WY02201
12394    WY02300
12395    WY02301
12396    WYDI050
Name: ORI, Length: 12397, dtype: object

In [149]:
crime.merge(agc[['ori', "STATE", "COUNTY"]], left_on='ORI', right_on='ori')#.sort_values(by=['STATE', 'ori']).dropna().groupby(['STATE', 'COUNTY', 'offense_code'])['count'].sum().reset_index()

          ORI  Person  Property    Society        ori STATE COUNTY
0   AL0200100     0.0       0.0        8.0  AL0200100    01    033
1   AL0490100    11.0       8.0       22.0  AL0490100    01    093
2   AL0540100     3.0       0.0       15.0  AL0540100    01    107
3   CA0349900     0.0       0.0       28.0  CA0349900    06    067
4   CA0360200   427.0     482.0   936930.0  CA0360200    06    071
5   CO0300100   350.0     642.0   639814.0  CO0300100    08    059
6   CO0600100    37.0      54.0      144.0  CO0600100    08    119
7   ID0010100   903.0     641.0  1198331.0  ID0010100    16    001
8   KS0890400     1.0       0.0        1.0  KS0890400    20    177
9   MS0250200     0.0       0.0       28.0  MS0250200    28    049
10  NJ0040700    14.0      21.0       14.0  NJ0040700    34    007
11  OK0160100   276.0     115.0    42414.0  OK0160100    40    031
12  OK0360100    19.0      14.0       57.0  OK0360100    40    071
13  OK0550200   103.0     172.0   385638.0  OK0550200    40    109
14  OK0560100    14.0      22.0     1281.0  OK0560100    40    111
15  OK0700100    37.0      35.0      105.0  OK0700100    40    139
16  TN0470100  1058.0    1949.0  3223964.0  TN0470100    47    093
17  TX2200200    50.0      36.0      230.0  TX2200200    48    439

In [158]:
# normalize agc ori: strip trailing zeros
agc["ORI_norm"] = agc["ori"].str.strip().str.upper().str.rstrip("0")

# normalize crime ORI: uppercase + trim
crime["ORI_norm"] = crime["ORI"].astype(str).str.strip().str.upper()

# quick sanity checks
agc[["ori","ORI_norm"]].head(), crime[["ORI","ORI_norm"]].head()

(         ori ORI_norm
 0  AL0430000    AL043
 1  AL0430200  AL04302
 2  AL0430100  AL04301
 3  AL0070300  AL00703
 4  AL0070200  AL00702,
        ORI ORI_norm
 0  AK00102  AK00102
 1  AK00104  AK00104
 2  AK00105  AK00105
 3  AK00106  AK00106
 4  AK00107  AK00107)

In [159]:
merged = agc.merge(crime, how="left", left_on="ORI_norm", right_on="ORI_norm")

In [160]:
merged

,state,county,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,...,STATE,COUNTY,NAME,LSAD,CENSUSAREA,ORI_norm,ORI,Person,Property,Society
0,AL,LEE,AL0430000,LEE,True,32.604064,-85.353048,AL,Alabama,Lee County Sheriff's Office,...,01,081,Lee,County,607.536,AL043,NaN,NaN,NaN,NaN
1,AL,LEE,AL0430200,LEE,True,32.604064,-85.353048,AL,Alabama,Opelika Police Department,...,01,081,Lee,County,607.536,AL04302,AL04302,73.0,116.0,686551.0
2,AL,LEE,AL0430100,LEE,True,32.608086,-85.475136,AL,Alabama,Auburn Police Department,...,01,081,Lee,County,607.536,AL04301,AL04301,89.0,149.0,627792.0
3,AL,BIBB,AL0070300,BIBB,True,33.015893,-87.127148,AL,Alabama,West Blocton Police Department,...,01,007,Bibb,County,622.582,AL00703,AL00703,1.0,8.0,1.0
4,AL,BIBB,AL0070200,BIBB,True,33.015893,-87.127148,AL,Alabama,Brent Police Department,...,01,007,Bibb,County,622.582,AL00702,AL00702,72.0,19.0,104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14227,WY,HOT SPRINGS,WY0090100,HOT SPRINGS,True,43.720871,-108.435652,WY,Wyoming,Thermopolis Police Department,...,56,017,Hot Springs,County,2004.092,WY00901,WY00901,11.0,4.0,204.0
14228,WY,NOT SPECIFIED,WYWHP0000,NOT SPECIFIED,True,41.167576,-104.841750,WY,Wyoming,Wyoming Highway Patrol,...,56,021,Laramie,County,2685.912,WYWHP,NaN,NaN,NaN,NaN
14229,WY,NOT SPECIFIED,WYDI05000,NOT SPECIFIED,True,43.055303,-108.605531,WY,Wyoming,Wind River Agency,...,56,013,Fremont,County,9183.814,WYDI05,NaN,NaN,NaN,NaN
14230,DC,NOT SPECIFIED,DCMPD0000,NOT SPECIFIED,True,38.894764,-77.015205,DC,District of Columbia,Washington Police Department,...,11,001,District of Columbia,,61.048,DCMPD,NaN,NaN,NaN,NaN
14231,DC,NOT SPECIFIED,DCMTP0000,NOT SPECIFIED,True,38.897390,-77.018940,DC,District of Columbia,Metro Transit Police,...,11,001,District of Columbia,,61.048,DCMTP,NaN,NaN,NaN,NaN

In [161]:
agc_only = set(agc["ORI_norm"]) - set(crime["ORI_norm"])
crime_only = set(crime["ORI_norm"]) - set(agc["ORI_norm"])

len(agc_only), len(crime_only)

(5775, 3940)

In [186]:
# keys
agc["ORI9"] = agc["ori"].astype(str).str.strip().str.upper()
crime["ORI7"] = crime["ORI"].astype(str).str.strip().str.upper()

# pad crime ORI to 9 chars (right-pad zeros)
crime["ORI9"] = crime["ORI7"].str.ljust(9, "0")

# unmatched counts using ORI9<->ORI9
agc_only = set(agc["ORI9"]) - set(crime["ORI9"])
crime_only = set(crime["ORI9"]) - set(agc["ORI9"])
len(agc_only), len(crime_only)

(2920, 1084)

In [187]:
merged = agc.merge(crime, how="inner", left_on="ORI9", right_on="ORI9")
merged

,state,county,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,...,LSAD,CENSUSAREA,ORI_norm_x,ORI9,ORI,Person,Property,Society,ORI_norm_y,ORI7
0,AL,LEE,AL0430000,LEE,True,32.604064,-85.353048,AL,Alabama,Lee County Sheriff's Office,...,County,607.536,AL043,AL0430000,AL04300,35.0,22.0,171933.0,AL04300,AL04300
1,AL,LEE,AL0430200,LEE,True,32.604064,-85.353048,AL,Alabama,Opelika Police Department,...,County,607.536,AL04302,AL0430200,AL04302,73.0,116.0,686551.0,AL04302,AL04302
2,AL,LEE,AL0430100,LEE,True,32.608086,-85.475136,AL,Alabama,Auburn Police Department,...,County,607.536,AL04301,AL0430100,AL04301,89.0,149.0,627792.0,AL04301,AL04301
3,AL,BIBB,AL0070300,BIBB,True,33.015893,-87.127148,AL,Alabama,West Blocton Police Department,...,County,622.582,AL00703,AL0070300,AL00703,1.0,8.0,1.0,AL00703,AL00703
4,AL,BIBB,AL0070200,BIBB,True,33.015893,-87.127148,AL,Alabama,Brent Police Department,...,County,622.582,AL00702,AL0070200,AL00702,72.0,19.0,104.0,AL00702,AL00702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11308,WY,HOT SPRINGS,WY0090000,HOT SPRINGS,True,43.647200,-108.208950,WY,Wyoming,Hot Springs County Sheriff's Office,...,County,2004.092,WY009,WY0090000,WY00900,5.0,2.0,48.0,WY00900,WY00900
11309,WY,HOT SPRINGS,WY0090100,HOT SPRINGS,True,43.720871,-108.435652,WY,Wyoming,Thermopolis Police Department,...,County,2004.092,WY00901,WY0090100,WY00901,11.0,4.0,204.0,WY00901,WY00901
11310,WY,NOT SPECIFIED,WYDI05000,NOT SPECIFIED,True,43.055303,-108.605531,WY,Wyoming,Wind River Agency,...,County,9183.814,WYDI05,WYDI05000,WYDI050,34.0,14.0,498.0,WYDI050,WYDI050
11311,DC,NOT SPECIFIED,DCMPD0000,NOT SPECIFIED,True,38.894764,-77.015205,DC,District of Columbia,Washington Police Department,...,,61.048,DCMPD,DCMPD0000,DCMPD00,2166.0,554.0,334701.0,DCMPD00,DCMPD00
11312,DC,NOT SPECIFIED,DCMTP0000,NOT SPECIFIED,True,38.897390,-77.018940,DC,District of Columbia,Metro Transit Police,...,,61.048,DCMTP,DCMTP0000,DCMTP00,680.0,169.0,41153.0,DCMTP00,DCMTP00

In [188]:
merged.columns

Index(['state', 'county', 'ori', 'counties', 'is_nibrs', 'latitude',
       'longitude', 'state_abbr', 'state_name', 'agency_name',
       'agency_type_name', 'nibrs_start_date', 'geometry', 'index_county',
       'id', 'STATE', 'COUNTY', 'NAME', 'LSAD', 'CENSUSAREA', 'ORI_norm_x',
       'ORI9', 'ORI', 'Person', 'Property', 'Society', 'ORI_norm_y', 'ORI7'],
      dtype='object')

In [189]:
len(merged['ORI'].unique())

11313

In [194]:
wip = walk.merge(acs, left_on=['STATEFP', 'COUNTYFP', 'GEO_ID'], right_on=['state', 'county', 'GEO_ID']).drop(['state', 'county', 'year'], axis=1)
wip

,STATEFP,COUNTYFP,walkability_min,walkability_max,walkability_mean,walkability_median,Ac_Total,Ac_Land,Ac_Unpr,Ac_Water,...,health_insance_coverage,poverty_status_for_families,poverty_status,household_internet_access,edu_total_pop_25plus,edu_high_school_grad,edu_bachelor_degree,edu_masters_degree,edu_professional_degree,edu_doctorate_degree
0,01,001,1.333333,10.000000,5.234375,4.666667,3.867879e+05,3.804357e+05,373158.784172,6352.190063,...,56955.0,15321.0,43549.0,21856.0,39614.0,10458.0,6507.0,3649.0,524.0,464.0
1,01,003,1.000000,12.500000,6.450355,6.250000,1.297424e+06,1.017464e+06,932574.210538,279959.572480,...,224339.0,58062.0,172151.0,87190.0,161977.0,36186.0,33379.0,13884.0,3059.0,2240.0
2,01,005,2.000000,11.000000,5.188406,4.666667,5.788771e+05,5.663928e+05,534293.333471,12484.285931,...,22295.0,5860.0,16708.0,9088.0,17995.0,5204.0,1212.0,520.0,164.0,111.0
3,01,007,2.000000,9.500000,5.033333,4.833333,4.007393e+05,3.983666e+05,318129.780484,2372.676192,...,21000.0,5018.0,16317.0,7083.0,16057.0,5556.0,1276.0,476.0,93.0,68.0
4,01,009,1.833333,8.500000,4.666667,4.500000,4.163930e+05,4.126827e+05,412305.399557,3710.321896,...,58437.0,15213.0,43232.0,21300.0,40668.0,11019.0,3783.0,1812.0,286.0,180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3214,72,145,1.000000,7.333333,4.359649,4.166667,4.363111e+04,2.934191e+04,28560.726899,14289.197491,...,54340.0,13226.0,44191.0,19799.0,39632.0,11200.0,6627.0,1945.0,208.0,208.0
3215,72,147,1.000000,6.000000,3.190476,2.333333,1.689507e+05,3.250388e+04,14005.014806,136446.845550,...,8317.0,1394.0,6734.0,2374.0,5970.0,2635.0,424.0,209.0,0.0,212.0
3216,72,149,1.333333,7.000000,3.254902,3.000000,2.370213e+04,2.280698e+04,22806.976400,895.154097,...,22237.0,5769.0,17770.0,7823.0,15523.0,5072.0,2658.0,535.0,51.0,89.0
3217,72,151,1.000000,7.333333,3.402778,2.833333,5.327419e+04,3.533658e+04,35006.627088,17937.610704,...,31042.0,7917.0,25436.0,11905.0,22690.0,5639.0,3353.0,511.0,34.0,53.0
3218,72,153,2.333333,7.333333,4.559524,4.833333,4.373600e+04,4.333440e+04,41374.334153,401.601499,...,34557.0,7318.0,28382.0,11836.0,25661.0,8381.0,5090.0,1075.0,134.0,352.0

In [198]:
fin = wip.merge(merged.groupby(["STATE", "COUNTY"], as_index=False)[["Person", "Property", "Society"]].sum(), left_on=['STATEFP', 'COUNTYFP'], right_on=['STATE', 'COUNTY'], how='inner')
fin

,STATEFP,COUNTYFP,walkability_min,walkability_max,walkability_mean,walkability_median,Ac_Total,Ac_Land,Ac_Unpr,Ac_Water,...,edu_high_school_grad,edu_bachelor_degree,edu_masters_degree,edu_professional_degree,edu_doctorate_degree,STATE,COUNTY,Person,Property,Society
0,01,001,1.333333,10.000000,5.234375,4.666667,3.867879e+05,3.804357e+05,3.731588e+05,6352.190063,...,10458.0,6507.0,3649.0,524.0,464.0,01,001,172.0,154.0,1244.0
1,01,003,1.000000,12.500000,6.450355,6.250000,1.297424e+06,1.017464e+06,9.325742e+05,279959.572480,...,36186.0,33379.0,13884.0,3059.0,2240.0,01,003,301.0,370.0,1982085.0
2,01,005,2.000000,11.000000,5.188406,4.666667,5.788771e+05,5.663928e+05,5.342933e+05,12484.285931,...,5204.0,1212.0,520.0,164.0,111.0,01,005,118.0,92.0,40437.0
3,01,007,2.000000,9.500000,5.033333,4.833333,4.007393e+05,3.983666e+05,3.181298e+05,2372.676192,...,5556.0,1276.0,476.0,93.0,68.0,01,007,110.0,50.0,405.0
4,01,009,1.833333,8.500000,4.666667,4.500000,4.163930e+05,4.126827e+05,4.123054e+05,3710.321896,...,11019.0,3783.0,1812.0,286.0,180.0,01,009,58.0,185.0,593.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2819,56,037,2.500000,13.500000,7.210784,7.750000,6.714197e+06,6.673122e+06,1.913513e+06,41075.495262,...,6658.0,3452.0,1280.0,436.0,226.0,56,037,120.0,102.0,223560.0
2820,56,039,2.666667,13.000000,7.833333,8.083333,2.698987e+06,2.557926e+06,7.554800e+04,141060.711641,...,2662.0,6758.0,2596.0,496.0,369.0,56,039,32.0,12.0,61366.0
2821,56,041,4.000000,12.333333,6.979167,6.333333,1.336380e+06,1.332272e+06,8.161035e+05,4108.239381,...,4003.0,1630.0,567.0,101.0,78.0,56,041,98.0,108.0,31097.0
2822,56,043,3.666667,13.333333,7.812500,7.333333,1.435297e+06,1.432720e+06,4.632301e+05,2577.155148,...,1110.0,935.0,391.0,75.0,18.0,56,043,33.0,36.0,171.0
2823,56,045,5.000000,9.333333,6.366667,5.666667,1.535981e+06,1.534690e+06,1.226056e+06,1291.220803,...,1529.0,678.0,138.0,41.0,43.0,56,045,15.0,14.0,69.0

In [200]:
pd.read_parquet(Path("data") / "gold" / "compiled_county_data.parquet")

FileNotFoundError: [Errno 2] No such file or directory: 'data/gold/compiled_county_data.parquet'